DROP SEQUENCE IF EXISTS food_id_seq;
CREATE SEQUENCE food_id_seq;

DROP SEQUENCE IF EXISTS workout_id_seq;
CREATE SEQUENCE workout_id_seq;

INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Lättmjölk', NULL, 39, 5, 3.5, 0.5, 'DAIRY', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Mellanmjölk', NULL, 47, 3.4, 5, 1.5, 'DAIRY', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Mellanfil', NULL, 45, 3.5, 3.8, 1.5, 'DAIRY', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Keso Mini', NULL, 70, 11, 2.5, 1.5, 'DAIRY', 250);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Keso (Cottage cheese)', 'Garant', 90, 12, 2, 4, 'DAIRY', 250);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Gräddfil', 'Garant', 140, 3, 3.5, 12, 'DAIRY', 320);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Vispgrädde 40% fett', NULL, 375, 2.1, 3.0, 40, 'DAIRY', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Matgrädde 15% fett', 'Garant', 160, 3, 4.5, 15, 'DAIRY', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kesella lätt', 'Arla', 75, 13, 3.5, 1, 'DAIRY', 250);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kesella naturell', 'Arla', 140, 10, 3.5, 1, 'DAIRY', 250);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kesella citrus', 'Arla', 170, 7.5, 17, 7.5, 'DAIRY', 250);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kvarg fettfri 0,5%', 'Milbona', 70, 12, 4, 0.5, 'DAIRY', 500);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kvarg naturell 0,3%', 'Lindahls', 64, 12, 3.4, 0.3, 'DAIRY', 500);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Crème fraiche - lätt 15%', 'Arla', 170, 3, 4, 15, 'DAIRY', 500);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Fetaost', NULL, 297, 17.5, 1.8, 24.7, 'DAIRY', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Fetaost', 'Fontana', 289, 16.5, 0.7, 22, 'DAIRY', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Halloumi', 'Fontana', 316, 22.5, 2.5, 24, 'DAIRY', 200);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Ost - Slices med Emmental', 'Kraft', 260, 17, 3.2, 18.5, 'DAIRY', 20);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Thaisoppa', 'Kelda', 70, 1.5, 7, 4, 'SOUP', 500);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Linssoppa', 'WeightWatchers', 43, 2.8, 6.2, 0.2, 'SOUP', 400);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Minestronesoppa', 'Findus', 50, 1.5, 8, 0.9, 'SOUP', 500);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Ägg', NULL, 137, 12.3, 0.4, 9.7, 'OTHER', 60);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Äggvita', NULL, 41, 10.1, 0.0, 0, 'OTHER', 40);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Omelett bas - 2 ägg, 2 äggvitor , 1g olja', NULL, 206, 22.8, 0.5, 12.6, 'DISH', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kokospannkaka (2 ägg, 2 äggvitor, kokos, mjölk)', NULL, 480.2, 30.64, 4.14, 36.94, 'DISH', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Thairätt - 13 (150g kyckling, 3g socker, 250g bambuskott, 30g kronärtskocka, 25g jordnötter, 25g olja)', NULL, 749, 55.9, 15.5, 50.8, 'DISH', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Avokado', NULL, 168, 2, 15.3, 4.4, 'GREENS', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Tomat', NULL, 23, 0.9, 3.7, 0.1, 'GREENS', 145);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Paprika', NULL, 29, 1.1, 4.4, 0.2, 'GREENS', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Äpple (litet)', NULL, 56, 0.1, 12.4, 0.1, 'GREENS', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Naturgodis - Apelsinchokladmandel', NULL, 490, 6.2, 65, 23, 'SWEETS', 9);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Naturgodis - Yoghurtmandel', NULL, 560, 9.7, 50.0, 37.1, 'SWEETS', 5);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kexchoklad', 'Cloetta', 510, 10, 59, 25, 'SWEETS', 55);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Sportlunch', 'Cloetta', 530, 9, 56, 30, 'SWEETS', 50);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Vit choklad', NULL, 585, 6, 52.4, 39.3, 'SWEETS', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kinder Maxi', 'Kinder', 564, 8.7, 53.5, 34.8, 'SWEETS', 21);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kinder Bueno', 'Kinder', 575, 9.2, 49.5, 37.3, 'SWEETS', 43);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Daim', 'Kraft foods', 530, 2.9, 59.9, 31, 'SWEETS', 28);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Nutrilett', NULL, 339, 34.7, 43.7, 7.6, 'POWDER', 33);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Proteinpulver - Latte macchiato', 'IronMaxx', 393, 75.2, 7.9, 6.0, 'POWDER', 21);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Proteinpulver - Whey 80', 'Star Nutrition', 410, 76, 5, 8, 'POWDER', 25);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Proteinpulver - Whey protein', 'Top Formula', 411, 80, 7, 7, 'POWDER', 25);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Proteinpulver - 100% Whey Protein Professional', 'Scitec Nutrition', 390, 73.3, 4.3, 4.3, 'POWDER', 30);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Naturdiet Orange Chocolate (extra vitamin C)', 'Friggs', 370, 23, 44, 9.5, 'BAR', 58);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Naturdiet Dark Chocolate (green tea)', 'Friggs', 340, 23, 37, 10, 'BAR', 60);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Naturdiet Choco Chocolate', 'Friggs', 380, 24, 42, 33, 'BAR', 58);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Naturdiet Crunchy Chocolate (Low Sugar High Protein)', 'Friggs', 380, 31, 29, 16, 'BAR', 50);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Naturdiet Rich Chocolate', 'Friggs', 45, 8, 1, 0.4, 'SHAKE', 310);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Nutrilett meal - Crispy Chocolate', 'Nutrilett', 373, 28.4, 37.3, 11.4, 'BAR', 60);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Nutrilett - Hunger Control, Brownie Bar', 'Nutrilett', 390, 26.2, 44.2, 11.7, 'BAR', 60);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Swebar Protein/energy bar - Pepparkaka', 'Dalblads', 380, 32, 44, 8, 'BAR', 55);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Cookie Caramel Crunch', 'OhYeah!', 400, 33, 38, 15.3, 'BAR', 85);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, '54% protein bar', 'Maxim', 405, 53.6, 13.5, 15.8, 'BAR', 80);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Diet bar', 'Oxygen', 325, 38.3, 21.8, 5.3, 'BAR', 50);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Low calorie bar - Dark Chocolate', 'Allévo', 370, 23, 39, 12, 'BAR', 57);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Tonfisk i olja', 'Pride', 215, 29, 0, 11, 'OTHER', 120);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Tonfisk i vatten', NULL, 106, 24.1, 0, 1, 'OTHER', 120);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Rökt skinka', 'Pärsons', 90, 18, 1, 3, 'MEAT', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Rökt Emilskinka', 'Pärsons', 100, 22, 1, 3, 'MEAT', 120);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Rökt salami', 'Pärsons', 460, 14, 3, 44, 'MEAT', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Rökt kalkonbröst', 'Garant', 100, 19, 1, 2, 'MEAT', 120);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Biff nötfärs (stekt)', NULL, 166, 17.2, 7, 7.6, 'MEAT', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Rostbiff', 'Livsmedelsverket', 118, 21.2, 0, 3.6, 'MEAT', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Fläsk (stekt)', NULL, 198, 26.7, 0, 10.1, 'MEAT', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kabanoss - Classic', 'Morliny', 356, 22.6, 0.5, 29.3, 'MEAT', 30);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Prinskorv', 'Wurst Master', 250, 13, 5, 19, 'MEAT', 270);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Prinskorv med tunt skinn', 'Scan', 260, 10, 4, 23, 'MEAT', 600);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kebabkött - djupfryst', NULL, 241, 14.3, 2.9, 18.6, 'MEAT', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Nötfärs (10%)', NULL, 149, 20, 0, 7.6, 'MEAT', 300);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Pepparbiff (stekt)', NULL, 148, 26.4, 0, 4.7, 'MEAT', 300);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Delikatessköttbullar', 'Scan', 260, 15, 6, 19, 'OTHER', 450);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kyckling ugnsstekt', NULL, 134, 27.5, 0, 2.5, 'MEAT', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kyckling wokad', NULL, 164, 29.4, 0, 5, 'MEAT', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kycklingbröstfilé mörad med saltlake (900g, 80%)', 'Eldorado', 90, 18, 1, 2, 'MEAT', 720);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kycklingspett', NULL, 170, 18, 0, 11, 'MEAT', 35);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Yakiniku (entrecote)', NULL, 197, 23.8, 0, 11.5, 'MEAT', 230);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Ölkorv - Red Devil', 'Ridderheims', 360, 34, 1, 25, 'MEAT', 50);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Korv - Sremska', 'Garant', 270, 13, 2, 24, 'MEAT', 300);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Korv - Chorizo de Pimentón', 'Scan', 300, 14, 4, 25, 'MEAT', 240);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Korv - Cabanosy', 'Freistat Bayern', 300, 14, 4, 28, 'MEAT', 270);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Hamburgare', 'Scan', 240, 15, 6, 17, 'MEAT', 90);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Grillad rostbiff', 'Jakobsdals', 130, 21, 1, 5, 'MEAT', 400);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Må Bättre Råg', 'Fazer', 220, 7.5, 45, 1, 'BREAD', 25);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Tortillabröd', 'Eldorado', 300, 8.5, 49, 7.5, 'BREAD', 40);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Vitt bröd', NULL, 269, 8.6, 50.4, 2.4, 'BREAD', 25);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Hamburgerbröd stora (4 bröd, 300g)', 'Eldorado', 280, 8, 51, 4, 'BREAD', 75);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Pasta - Integrall (fullkorn)', 'Barilla', 351, 12.5, 66.7, 2.5, 'OTHER', 50);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Nudlar (äggnudlar)', NULL, 377, 14, 68.2, 4.2, 'PASTA', 50);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Sallad (50g pasta, 120g kyckling, ½ägg, 50g feta, 60g tomat)', NULL, 172.8, 16.7, 11.6, 5.9, 'MEAT', 310);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Sushi - lax (7g lax)', NULL, 144, 8.5, 16.3, 4.8, 'OTHER', 25);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Olivolja', NULL, 884, 0, 0, 100, 'OTHER', 10);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Sweet chillisås - Chilli & garlic sauce', 'Suree', 118, 0.7, 28.2, 0.3, 'OTHER', 20);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Chillisås - Sriracha Chilli Souce (½dl=75g)', 'Pantainorasingh Brand', 132, 1.1, 30.0, 0.9, 'OTHER', 75);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kokosflingor', 'Eldorado', 610, 7, 6.5, 62, 'OTHER', 200);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Taco kryddmix', 'Garant (PrisExtra)', 310, 9.2, 54, 1, 'OTHER', 40);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Taco Sauce - Hot', 'Santa Maria', 35, 1.5, 6.0, 0.3, 'OTHER', 230);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Ris', NULL, 113, 2.4, 25, 0.2, 'OTHER', 300);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Socker', NULL, 405, 0, 99.6, 0, 'OTHER', 3);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Bambuskott', NULL, 24, 1.7, 3.1, 0.4, 'GREENS', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kronärtskocka', NULL, 52, 2.7, 7.3, 0.2, 'GREENS', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Jordnötter', NULL, 600, 27, 10.3, 49, 'OTHER', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Valnötter', NULL, 669, 14.3, 13, 62, 'NUTS', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Cachewnötter', NULL, 590, 15.3, 25.9, 46.5, 'NUTS', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kokosmjölk', NULL, 197, 2, 2.8, 21.3, 'OTHER', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Pizza (Vesuvio/Calzone)', NULL, 1115, 58, 107, 49, 'DISH', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Vårrulle (restaurang)', NULL, 316, 6.6, 18.7, 23.8, 'DISH', 15);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Jordnötssås (1 skopa, ~0,75dl=50g)', NULL, 324, 5.3, 15.4, 26.7, 'DISH', 50);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Thairätt - Kyckling i kokosmjölk, buffé (340g kyckling, 40g kokosmjölk, 90g bambuskott)', NULL, 572.8, 96.4, 8.9, 18.5, 'DISH', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Öl - 5.6%', NULL, 47, 0.6, 3.2, 0, 'OTHER', 330);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Öl - 7%', NULL, 57.5, 0.6, 3.2, 0, 'OTHER', 330);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Krossade tomater - chilli', 'Garant', 30, 0.9, 5.8, 0.1, 'GREENS', 390);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Majonäs (90% fett)', NULL, 800, 1.2, 0.6, 89.6, 'OTHER', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Salladsbarens dressing (45g)', NULL, 134, 0.5, 0.4, 14.6, 'DISH', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Salladsbarens sallad (140g kyckling, 40g pasta, 20g fetaost, 10g avokado, ½ ägg)', NULL, 445.3, 50.9, 28.7, 12.8, 'DISH', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kokosmjölk krämig', 'Eldorado', 180, 1.8, 3, 18, 'OTHER', 250);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Wokgrönsaker Thai - bamboo shoots & baby corn', 'Findus', 30, 1, 4, 3.5, 'GREENS', 500);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Brocolli', NULL, 35, 3.5, 3.1, 0.3, 'GREENS', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Blomkål', NULL, 28, 1.6, 3.9, 0.2, 'GREENS', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Majs (burk)', 'Bonduelle', 80, 2.9, 10.8, 0.5, 'GREENS', 140);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Potatis - kokt', NULL, 83, 1.8, 17.5, 0.1, 'GREENS', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Satay sauce - Jordnötssås', 'Santa Maria', 250, 6.5, 22, 16, 'OTHER', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Lax', NULL, 181, 18.4, 0, 12, 'OTHER', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Lax - gravad', NULL, 179, 21.2, 2.7, 9.2, 'OTHER', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Wok hemmagjord (240g kyckling, 80g kokosmjölk, 170g wokgrönsaker)', NULL, 451, 50, 15, 6, 'DISH', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Pannkaka (3 ägg, 3 äggvitor,  ½dl rågmjöl, 1dl lättmjölk)', NULL, 500, 42, 19, 29, 'DISH', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Rismjöl', NULL, 347, 6, 75.3, 1.4, 'OTHER', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Rågmjöl (grovt, 1dl=50g)', 'Kungsörnen', 310, 8.5, 57, 2, 'OTHER', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Farinsocker', NULL, 388, 0, 95.5, 0, 'OTHER', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Choklad - Mörk >70%', NULL, 572, 9.7, 50.7, 37, 'OTHER', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Sesamboll (14g rismjöl, 4g farinsocker, 1g mörk choklad, 1g olja) ', NULL, 78.7, 0.9, 14.9, 1.6, 'DISH', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Dumplings (7g vetemjöl/10g deg + 10g fyllning)', NULL, 24.6, 0.6, 5, 0.1, 'DISH', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Tofu', NULL, 74, 7.8, 0, 4.2, 'OTHER', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Protein shake', 'Maxim', 74, 6, 12, 0.2, 'OTHER', 330);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Protein Bar - Crispy chocolate & banana', 'Naturamino', 349, 33.3, 28.6, 10.1, 'BAR', 60);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Popcorn - Original', 'Olw', 480, 9, 60, 22, 'OTHER', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Stora vita böno (konserv)', NULL, 107, 6.9, 14.6, 0.8, 'BEANS', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Marsipan', NULL, 406, 5.2, 75.2, 9.4, 'SWEETS', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Morotsaft (gulrotsdrikk)','Granini', 29, 0, 6.8, 0, 'JUICE', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Nypressad apelsin','Brämhults', 45, 1, 9, 0, 'JUICE', 250);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Nypressad apelsin och blodgrape','Brämhults', 41, 1, 9, 0, 'JUICE', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Tomatketchup - Svartpeppar', 'Felix', 100, 1.5, 22, 0.5, 'OTHER', 30);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Gainomax Recovery', NULL, 100, 8.0, 9.9, 0.3, 'OTHER', 250);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Special Muesli - Luxury Fruit & Nut', 'Simply Sumptuous', 398, 8.0, 57.6, 13.8, 'MUESLI', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Crunchy - Yoghurt & jordgubb (1dl = 50g)', 'Garant', 460, 9.1, 62, 17, 'MUESLI', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kidneybönör', NULL, 110, 8.8, 13.4, 0.7, 'GREENS', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Gröna linser', NULL, 92, 6.3, 13.1, 0.6, 'GREENS', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Proteinbar - apple & yoghurt 60g', 'Nutramino', 400, 33, 40, 12, 'BAR', 60);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Torsk', NULL, 78, 33, 0, 0.5, 'FISH', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Torsk - panerad', NULL, 141, 17.2, 4.7, 5.9, 'FISH', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Punschpralin', 'Cloetta', 445, 0.7, 79, 13, 'SWEETS', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Chili con Carne', 'Felix', 90, 6.1, 7.7, 4.1, 'OTHER', 560);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Youghurt-glass 7-Eleven', '7-Eleven', 95, 3, 19, 0.5, 'SWEETS', 160);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Tårta - Bärtårta grädde vaniljkräm sylt gelé', 'Livsmedelsverket', 245, 3.2, 31.4, 11.1, 'SWEETS', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Jordgubbe (10g-20g)', 'Livsmedelsverket', 41, 0.5, 8.3, 0.2, 'GREENS', 15);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Quinoa', 'Frebaco', 400, 12, 73, 4, 'OTHER', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Ombar - Cranberry & Mandarin', 'Vegan', 483, 5.7, 44.1, 35.3, 'OTHER', 35);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Blodpudding', 'Gea', 220, 8, 27, 9, 'OTHER', 500);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Rådöda lingon', 'Coop', 190, 0, 45, 0, 'OTHER', 750);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Havregrynsgröt', 'Coop Änglamark', 340, 13, 56, 7, 'OTHER', 35);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Rotfruktsmix', 'Garant', 35, 1.1, 5.1, 0.3, 'GREENS', 600);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Vegobullar', 'Anamma', 182, 13, 2.2, 9.5, 'OTHER', 300);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Vegoburgare', 'Anamma', 181, 13, 2, 9.4, 'OTHER', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Lättglass vanilj (500ml = 240g)', 'GB', 120, 5, 11, 5, 'OTHER', 240);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Morot (liten ~80g, jätte ~200g)', NULL, 36.4, 0.7, 6.6, 0.24, 'GREENS', 100);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Kokosmjölkspulver (coconut milk powder mix, 1dl=60g)', 'Maggi', 685, 7, 25, 62, 'OTHER', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Torskfiskpinne (1 pinne = 25g)', 'Findus', 210, 13, 18, 9, 'FISH', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Bönpasta Fettuccine', 'Risenta', 360, 44, 18, 9, 'OTHER', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Grönsakskaka (1 kaka = 60g)', 'Ikea', 175, 3.1, 13, 11, 'GREENS', 600);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Ölkorv (Hot Amigo)', 'Ridderheims', 480, 29, 2.4, 38, 'MEAT', 50);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Protein Bar Coconut', 'Nutramino', 439, 31, 33, 21, 'BAR', 66);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Korv - Sorunda Chorizo (1 korv=120g)', 'Sorunda korvfabrik', 240, 15, 6, 17, 'MEAT', 600);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Krossade tomater', 'ICA', 20, 0.8, 3.7, 0.5, 'GREENS', 500);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Gräddglass - gammaldags vanilj ', 'GB', 117, 18, 4, 16, 'SWEETS', 250);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Maxim Protein Boost', 'Maxim', 68, 10, 5.6, 0.4, 'OTHER', 480);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Maxim Protein Boost', 'Maxim', 68, 10, 5.6, 0.4, 'OTHER', 480);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Couscous tillagad', NULL, 108.1, 3.8, 21.9, 0.2, 'OTHER', NULL);
INSERT INTO food (id, version, name, brand, kcal, protein, carbohydrate, fat, category, pack_size_in_grams) VALUES(nextval('food_id_seq'), 0, 'Fläskfilé', 'Livsmedelsverket', 106.7, 20.6, 0, 2.6, 'MEAT', NULL);
INSERT INTO workout_type (id, version, name, average_kcal) VALUES(nextval('workout_id_seq'), 0, 'Bodycombat', 800);
INSERT INTO workout_type (id, version, name, average_kcal) VALUES(nextval('workout_id_seq'), 0, 'Bodypump', 600);
INSERT INTO workout_type (id, version, name, average_kcal) VALUES(nextval('workout_id_seq'), 0, 'Zumba', 650);
INSERT INTO workout_type (id, version, name, average_kcal) VALUES(nextval('workout_id_seq'), 0, 'Functional Moves', 500);
INSERT INTO workout_type (id, version, name, average_kcal) VALUES(nextval('workout_id_seq'), 0, 'Gång 200kcal/30min', 200);
INSERT INTO workout_type (id, version, name, average_kcal) VALUES(nextval('workout_id_seq'), 0, 'Löpning 120kcal/10min', 120);
INSERT INTO workout_type (id, version, name, average_kcal) VALUES(nextval('workout_id_seq'), 0, 'Styrketräning', 400);
INSERT INTO workout_type (id, version, name, average_kcal) VALUES(nextval('workout_id_seq'), 0, 'Löpning 1 mil', 800);
INSERT INTO workout_type (id, version, name, average_kcal) VALUES(nextval('workout_id_seq'), 0, 'Spinning 1h', 600);
INSERT INTO workout_type (id, version, name, average_kcal) VALUES(nextval('workout_id_seq'), 0, 'Box 1h', 500);
INSERT INTO workout_type (id, version, name, average_kcal) VALUES(nextval('workout_id_seq'), 0, 'Grit Strength', 450);
INSERT INTO users (id, version, admin, kcal_per_day, name, password) values (1, 0, TRUE , 2000.0, 'user', 'secret');